name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git reset --hard

      - name: Copy dist files
        run: |
          rm -rf *
          cp -r dist/* .
          rm -rf dist

      - name: Copy docs folder from main branch
        run: |
          git checkout main -- docs
          mv docs .

      - name: Push to gh-pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
